name: financial_note
description: A financial note application.

dependencies:
  flutter:
    sdk: flutter
  intl: "^0.15.1"
  intl_translation: "^0.15.0"
  http: ">=0.11.3+14"
  isolate: ">=1.1.0"
  url_launcher: "^0.4.2+5"
  google_sign_in: "^1.0.1"
  firebase_analytics: "^0.1.1"
  firebase_auth: "^0.3.1"
  firebase_database: "^0.1.2"
  firebase_storage: "^0.0.7"
  firebase_messaging: "^0.0.7"
  shared_preferences: "^0.2.5"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
   - assets/drawer_header.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/.

  # To add assets from package dependencies, first ensure the asset
  # is in the lib/ directory of the dependency. Then,
  # refer to the asset with a path prefixed with
  # `packages/PACKAGE_NAME/`. The `lib/` is implied, do not
  # include `lib/` in the asset path.
  #
  # Here is an example:
  #
  # assets:
  #  - packages/PACKAGE_NAME/path/to/asset

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
